from app.vectorstore.chroma_service import ChromaService

from app.agents.state import AgentState


class CodeSearchAgent:
    """
    Agent responsible for retrieving code-level evidence
    for repository questions.
    """

    def __init__(self):
        self.chroma_service = ChromaService()

    def search(self, state: AgentState) -> AgentState:
        """
        Retrieve code evidence using the search queries
        generated by the Query Planner.
        """

        repository_name = state["repository_name"]

        search_queries = state.get(
            "search_queries",
            [],
        )

        if not search_queries:
            search_queries = [
                (
                    f"code implementation function "
                    f"class method logic {state['question']}"
                )
            ]

        all_chunks = []

        for query in search_queries:

            print(
                f"[CodeSearchAgent] Search query: "
                f"{query}"
            )

            retrieved_chunks = (
                self.chroma_service.search_chunks(
                    repository_name=repository_name,
                    query=query,
                    top_k=5,
                )
            )

            all_chunks.extend(
                retrieved_chunks
            )

        # -----------------------------------------
        # Remove duplicate chunks
        # -----------------------------------------

        unique_chunks = {}

        for chunk in all_chunks:

            chunk_key = (
                f"{chunk.get('file_path', '')}:"
                f"{chunk.get('chunk_index', 0)}"
            )

            if chunk_key not in unique_chunks:
                unique_chunks[chunk_key] = chunk

        retrieved_chunks = list(
            unique_chunks.values()
        )

        print(
            f"[CodeSearchAgent] Total unique evidence "
            f"chunks: {len(retrieved_chunks)}"
        )

        return {
            **state,
            "retrieved_chunks": retrieved_chunks,
        }


code_search_agent = CodeSearchAgent()


def code_search_node(
    state: AgentState,
) -> AgentState:
    """
    LangGraph node wrapper for the Code Search Agent.
    """

    return code_search_agent.search(state)